### PR TITLE
Allow to use timer and meter as decorators and with context manager

### PR DESCRIPTION
**Pull request by misiek08**
Possible usage:
```python
def test_context():
    for i in range(0, 5000):
        with Metrology.meter('meter_context_5000'):
            pass

@Metrology.meter('meter_decorator')
def text_decorator():
    pass
```
This change applies only to **timer** and **meter**

### CODE REVIEW

**Comment by vi4m** [comment]
Cool!

**Comment by ar4s** [comment]
shut-up-and-take-my-money1

**Comment by xliiv** [comment]
Awsome

**Comment by cyberdelia** [comment]
Can you look into adding tests and documentation?

**Comment by misiek08** [comment]
I've just added tests for new functionality and wrote example to ReadME, so everyone can use it :)

**Comment by cyberdelia** [comment]
Thanks :bowtie:

**Pull request merged**
