### PR TITLE
For timer/meter decorators, return the return value

### PR DESCRIPTION
**Pull request by steven-lai**
For https://github.com/cyberdelia/metrology/issues/34

### CODE REVIEW

**Comment by cyberdelia** [comment]
Would you mind adding tests too? Thank you so much.

**Comment by steven-lai** [comment]
Updated with unit tests, let me know if I can improve it in anyways.

**Comment by cyberdelia** [comment]
@steven-lai Add yourself to the ``AUTHORS`` file? And I will cut a release.

**Comment by steven-lai** [comment]
Done, thanks for the reminder!

**Pull request merged**
